AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  # CF Settings
  TemplateBucket:
    Description: S3 bucket name that have templates. The nested templates forlder should reside in bucket-name/static.
    Type: String
    Default: data-quest-infra

  Environment:
    Description: Environment Name
    Type: String
    Default: prod

  S3Bucket:
    Description: S3 bucket
    Type: String
    Default: data-quest

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ "", ['https://s3.amazonaws.com/', !Ref TemplateBucket,"/", 'network/vpc.yml'] ]
      Parameters:
        Environment: prod
        VpcName: data-quest

  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ "", ['https://s3.amazonaws.com/', !Ref TemplateBucket,"/", 'iam/roles.yml'] ]
      Parameters:
        S3Bucket: !Ref S3Bucket

  Glue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ "", ['https://s3.amazonaws.com/', !Ref TemplateBucket,"/", 'analytics/aws-glue.yml'] ]
      Parameters:
        GlueRole: !GetAtt IAM.Outputs.GlueRole
        GlueRoleARN: !GetAtt IAM.Outputs.GlueRoleArn
        S3Bucket: !Ref S3Bucket

  SageMaker:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ "", ['https://s3.amazonaws.com/', !Ref TemplateBucket,"/", 'sagemaker/notebook.yml'] ]
      Parameters:
        Identifier: data-quest-notebook
        VPC: !GetAtt VPC.Outputs.VPC
        Subnet: !GetAtt VPC.Outputs.PublicSubnet1
        SagemakerRole: !GetAtt IAM.Outputs.SagemakerRoleArn